### ISSUE TITLE
License for repo

### ISSUE THREAD

**Issue by lannelin** [YuanGongND/multichannel-antispoof#1]
Hi Yuan. Thanks for your work on ReMASC! Just trying to get a baseline to work from and wanted to run your network here against a split of the data. Would it be possible to add a license to the repository, if you are happy for it to be used freely?

Thanks!

**Comment by YuanGongND** [comment]
Hi there,

I just added a BSD license. 

Best,
Yuan

**Comment by lannelin** [comment]
thanks!
